version: "3.8"
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8081:8080"
    restart: always

  postgres:
    container_name: postgres-base
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volume:
      - ./postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - postgres-network
